version: '3'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    # env_file:
    #   - environments.env
    networks:
      - jenkins_network

  ngrok:
    image: ngrok/ngrok
    volumes:
      - ./ngrok:/ngrok
    command: ["start", "--config=/ngrok/ngrok.yml", "jenkins"]
    ports:
      - "4040:4040"
    # env_file:
    #   - environments.env
    networks:
      - jenkins_network

volumes:
  jenkins-data:

networks:
  jenkins_network:
